development:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['host'] %>
  database: <%= ENV['database'] %>
  username: <%= ENV['username'] %>
  port: <%= ENV['port'] %>
  password: <%= ENV['password'] %>

test:
  adapter: sqlite3
  database: db/development.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  host:
  database:
  username:
  port:
  password:
