development:
  adapter: postgresql
  encoding: unicode
  host:
  database:
  username:
  port:
  password:

test:
  adapter: sqlite3
  database: db/development.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  host:
  database:
  username:
  port:
  password:
